# permissions for end users to edit elasticwebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elasticweb
    app.kubernetes.io/managed-by: kustomize
  name: elasticweb-editor-role
rules:
- apiGroups:
  - elasticweb.com.zhh
  resources:
  - elasticwebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticweb.com.zhh
  resources:
  - elasticwebs/status
  verbs:
  - get
