# permissions for end users to view elasticwebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elasticweb
    app.kubernetes.io/managed-by: kustomize
  name: elasticweb-viewer-role
rules:
- apiGroups:
  - elasticweb.com.zhh
  resources:
  - elasticwebs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticweb.com.zhh
  resources:
  - elasticwebs/status
  verbs:
  - get
