apiVersion: elasticweb.com.zhh/v1
kind: ElasticWeb
metadata:
  labels:
    app.kubernetes.io/name: elasticweb
    app.kubernetes.io/managed-by: kustomize
  name: elasticweb-sample
spec:
  # TODO(user): Add fields here
